### ISSUE TITLE
Printer Columns: Show Connected Email Address

### ISSUE THREAD

**Issue by rawkode** [rawkode/chappaai#14]
on the callback function, get the connected account ID / email and store on the status and add a printer column

**Comment by nitishm** [comment]
> on the callback function, get the connected account ID / email and store on the status and add a printer column

Is this the `clientID` from the `Secret`? Or is there another way to retrieve this?

**Comment by rawkode** [comment]
I don't think this is possible without making requests to the API on the users behalf, and I'm not sure we should.
